// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm1MliO-i-acvpZ_7ET8OqMFakR-aZ_yM',
    appId: '1:469747224129:web:e7bb9c03509f1dd8b080c0',
    messagingSenderId: '469747224129',
    projectId: 'anchoitieudung',
    authDomain: 'anchoitieudung.firebaseapp.com',
    databaseURL: 'https://anchoitieudung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anchoitieudung.appspot.com',
    measurementId: 'G-G3TLH8ZRZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE5-6I6oUgEmOSIPFS23uabPTeJVPsuKA',
    appId: '1:469747224129:android:b59e4d339c6a45f3b080c0',
    messagingSenderId: '469747224129',
    projectId: 'anchoitieudung',
    databaseURL: 'https://anchoitieudung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anchoitieudung.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcW-WKcXu_WsBgPeaukrWdhvx3GrN0Nco',
    appId: '1:469747224129:ios:4a2575b8e676b460b080c0',
    messagingSenderId: '469747224129',
    projectId: 'anchoitieudung',
    databaseURL: 'https://anchoitieudung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anchoitieudung.appspot.com',
    iosBundleId: 'com.example.anchoitieudung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcW-WKcXu_WsBgPeaukrWdhvx3GrN0Nco',
    appId: '1:469747224129:ios:4a2575b8e676b460b080c0',
    messagingSenderId: '469747224129',
    projectId: 'anchoitieudung',
    databaseURL: 'https://anchoitieudung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anchoitieudung.appspot.com',
    iosBundleId: 'com.example.anchoitieudung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm1MliO-i-acvpZ_7ET8OqMFakR-aZ_yM',
    appId: '1:469747224129:web:b1427acd5f100b97b080c0',
    messagingSenderId: '469747224129',
    projectId: 'anchoitieudung',
    authDomain: 'anchoitieudung.firebaseapp.com',
    databaseURL: 'https://anchoitieudung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anchoitieudung.appspot.com',
    measurementId: 'G-Q34W847PXT',
  );
}
